export const GET_DATA_PRODUCTS = 'GET_DATA_PRODUCTS'
export const POST_DATA_PRODUCTS = 'POST_DATA_PRODUCTS'
export const PUT_DATA_PRODUCTS = 'PUT_DATA_PRODUCTS'
export const DELETE_DATA_PRODUCTS = 'DELETE_DATA_PRODUCTS'